# Generated by Django 4.2.2 on 2023-06-18 19:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Book",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=30)),
                ("author", models.CharField(max_length=50)),
                ("genre", models.CharField(max_length=20)),
                ("pub_date", models.DateTimeField(verbose_name="date published")),
            ],
        ),
        migrations.CreateModel(
            name="Bookshelf",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("shelf_number", models.IntegerField(default=0)),
                ("capacity", models.IntegerField(default=0)),
            ],
        ),
        migrations.AddConstraint(
            model_name="bookshelf",
            constraint=models.CheckConstraint(
                check=models.Q(("capacity", 5)), name="max_capacity"
            ),
        ),
        migrations.AddField(
            model_name="book",
            name="bookshelf",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="books.bookshelf"
            ),
        ),
    ]
