# Generated by Django 4.2.2 on 2023-06-18 19:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("books", "0001_initial"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="bookshelf",
            name="max_capacity",
        ),
        migrations.AddConstraint(
            model_name="bookshelf",
            constraint=models.CheckConstraint(
                check=models.Q(("capacity__lte", 5)), name="max_capacity"
            ),
        ),
    ]
