# Generated by Django 4.2.2 on 2023-07-11 19:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("books", "0006_bookqueue"),
    ]

    operations = [
        migrations.AddField(
            model_name="bookqueue",
            name="queue_date",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 7, 11, 21, 5, 29, 715540),
                verbose_name="queue date",
            ),
        ),
    ]
