# Generated by Django 4.2.2 on 2023-07-09 21:14

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("members", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Book",
        ),
    ]
